const $=id=>document.getElementById(id);let selectedFiles=[],rawMarkdown='',availableModels=[],scanTimer,draftTimer;
const fields=['subject','grade','lesson','book','periods','students','classSize','equipment','notes'];
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
// Escape đủ 5 ký tự đặc biệt (bao gồm dấu nháy) để dùng an toàn cả trong nội dung text lẫn trong thuộc tính HTML (title, style, stroke...).
// Trước đây hàm này chỉ escape &,<,> nên các chỗ dùng esc() để build thuộc tính (vd aria-label, style="--c:...") có thể bị phá vỡ nếu dữ liệu AI trả về chứa dấu ".
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('themeBtn').onclick=()=>document.body.classList.toggle('dark');
$('showKey').onclick=()=>{const i=$('apiKey');i.type=i.type==='password'?'text':'password';$('showKey').textContent=i.type==='text'?'Ẩn':'Hiện'};
function modelScore(name){const n=name.toLowerCase(),version=(n.match(/gemini-(\d+(?:\.\d+)?)/)||[])[1];let score=parseFloat(version||0)*100;if(n.includes('flash'))score+=30;if(n.includes('pro'))score+=20;if(n.includes('lite'))score-=8;if(/preview|experimental|exp/.test(n))score-=12;if(n.includes('latest'))score-=4;return score}
function usableModel(m){const n=(m.name||'').toLowerCase();return n.startsWith('models/gemini-')&&(m.supportedGenerationMethods||[]).includes('generateContent')&&!/(embedding|image|imagen|veo|tts|audio|transcribe|live|computer-use|robotics)/.test(n)}
function setModelStatus(text,state=''){$('modelStatus').textContent=text;$('modelStatus').className=`model-status ${state}`.trim()}
async function scanModels(showToast=false){const key=$('apiKey').value.trim();if(!key){availableModels=[];$('model').innerHTML='<option value="auto">Tự động dò mô hình phù hợp (Khuyên dùng)</option>';setModelStatus('Nhập API key để hệ thống tự dò mô hình đang hoạt động.');if(showToast)toast('Vui lòng nhập Gemini API key');return []}const btn=$('scanModels'),previous=$('model').value;btn.disabled=true;setModelStatus('Đang dò các mô hình có thể tạo nội dung...');try{const res=await fetch('https://generativelanguage.googleapis.com/v1beta/models',{headers:{'x-goog-api-key':key}}),data=await res.json();if(!res.ok)throw new Error(data?.error?.message||'Không lấy được danh sách mô hình');availableModels=(data.models||[]).filter(usableModel).sort((a,b)=>modelScore(b.name)-modelScore(a.name));if(!availableModels.length)throw new Error('API key này chưa có mô hình tạo nội dung phù hợp');$('model').innerHTML='<option value="auto">Tự động chọn mô hình tốt nhất (Khuyên dùng)</option>'+availableModels.map(m=>`<option value="${esc(m.name)}">${esc(m.displayName||m.name.replace('models/',''))}</option>`).join('');if([...$('model').options].some(o=>o.value===previous))$('model').value=previous;setModelStatus(`Đã tìm thấy ${availableModels.length} mô hình · ưu tiên ${availableModels[0].name.replace('models/','')}`,'ok');if(showToast)toast(`Đã tìm thấy ${availableModels.length} mô hình đang hỗ trợ`);return availableModels}catch(err){availableModels=[];$('model').innerHTML='<option value="auto">Tự động dò khi bắt đầu soạn</option>';setModelStatus(err.message||'Không thể dò mô hình','error');if(showToast)toast(err.message||'Không thể dò mô hình');return []}finally{btn.disabled=false}}
$('scanModels').onclick=()=>scanModels(true);
$('apiKey').addEventListener('input',()=>{clearTimeout(scanTimer);scanTimer=setTimeout(()=>scanModels(false),700)});
$('sampleBtn').onclick=()=>{Object.entries({subject:'Toán',grade:'12',lesson:'Bài 2. Giá trị lớn nhất và giá trị nhỏ nhất của hàm số',book:'Kết nối tri thức với cuộc sống',periods:'3',students:'Trung bình–khá',classSize:'45',equipment:'TV 32 inch, bảng phụ, máy tính cầm tay'}).forEach(([k,v])=>$(k).value=v);toast('Đã điền dữ liệu mẫu')};
const dz=$('dropZone');['dragenter','dragover'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addFiles(e.dataTransfer.files));dz.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('files').click()}});$('files').onchange=e=>addFiles(e.target.files);
function addFiles(list){for(const f of list){if(f.size>20*1024*1024){toast(`${f.name}: vượt 20 MB`);continue}if(!selectedFiles.some(x=>x.name===f.name&&x.size===f.size))selectedFiles.push(f)}renderFiles()}
function renderFiles(){$('fileList').innerHTML=selectedFiles.map((f,i)=>`<div class="file-chip"><b>${esc(f.name)}</b><span>${(f.size/1048576).toFixed(1)} MB</span><button type="button" data-i="${i}" aria-label="Bỏ tệp">×</button></div>`).join('');$('fileList').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedFiles.splice(+b.dataset.i,1);renderFiles()})}
function values(){return Object.fromEntries(fields.map(k=>[k,$(k).value.trim()]))}
function setProgress(p,title,text){$('emptyState').hidden=true;$('result').hidden=true;$('progress').hidden=false;$('resultActions').hidden=true;$('progressBar').style.width=p+'%';$('progressTitle').textContent=title;$('progressText').textContent=text}
function bytesToBase64(buf){let bin='',arr=new Uint8Array(buf),step=0x8000;for(let i=0;i<arr.length;i+=step)bin+=String.fromCharCode(...arr.subarray(i,i+step));return btoa(bin)}
async function filePart(file){return {inlineData:{mimeType:file.type||mime(file.name),data:bytesToBase64(await file.arrayBuffer())}}}
function mime(n){const e=n.split('.').pop().toLowerCase();return {pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',txt:'text/plain',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}[e]||'application/octet-stream'}
// Chỉ hỗ trợ lớp 10–12 (đúng phạm vi min/max của #grade). Khoá về 10-12 để luôn tra được bảng mã.
function clampGrade(g){const n=parseInt(g,10);return Number.isFinite(n)?Math.min(12,Math.max(10,n)):12}

// Dựng khối "NGUỒN THAM CHIẾU BẮT BUỘC" nhúng thẳng bảng mã chính thức (KHÔNG để AI tự nhớ/tự bịa).
// Đây là điểm mấu chốt để tránh rủi ro AI gán sai/gán khống mã NLS, NLAI: hai văn bản
// (QĐ 2422/QĐ-BGDĐT và TT 02/2025/TT-BGDĐT) đều rất mới, mô hình AI nhiều khả năng
// KHÔNG có sẵn dữ liệu chính xác trong lúc huấn luyện nếu không được cấp trực tiếp ở đây.
function buildStandardsBlock(v){
  const grade=clampGrade(v.grade),digital=$('includeDigital').checked,ai=$('includeAI').checked;
  if(!digital&&!ai)return '';
  let out='\n===== NGUỒN THAM CHIẾU BẮT BUỘC (KHÔNG được suy diễn/bịa mã ngoài danh sách dưới đây) =====\n';
  if(ai){
    out+=`\n[BẢNG MÃ YÊU CẦU CẦN ĐẠT NĂNG LỰC AI — NLAI — Lớp ${grade}]\n`
       +`Trích Khung nội dung giáo dục AI, kèm theo Quyết định số 2422/QĐ-BGDĐT ngày 18/8/2026 của Bộ GDĐT.\n`
       +`Quy ước mã: [Lớp].[Mã chủ đề A/B/C/D+số].[Số thứ tự] — có tiền tố "MR" là nội dung MỞ RỘNG (không bắt buộc với mọi học sinh), không có "MR" là nội dung CỐT LÕI (bắt buộc).\n`
       +(AI_YCCD[grade]||'')+'\n';
  }
  if(digital){
    out+=`\n[BẢNG MÃ NĂNG LỰC SỐ — NLS — đầy đủ 24 năng lực thành phần x 8 bậc, áp dụng nhóm lớp 10-11-12]\n`
       +`Trích nguyên văn Phụ lục — Khung năng lực số cho người học (Thông tư 02/2025/TT-BGDĐT ngày 24/01/2025 của Bộ GDĐT).\n`
       +`Định dạng mã dùng ở đây: "[Miền].[Tiểu mục]-B[Số bậc][ý]" (vd 6.3-B5a = Miền 6, tiểu mục 3, Bậc 5, ý a). Đây là quy ước tự đặt để tiện tham chiếu (Thông tư gốc chỉ gọi "Bậc 1".."Bậc 8", không có ký hiệu viết tắt chính thức) — Bậc 1-2 ứng Cơ bản, 3-4 Trung cấp, 5-6 Nâng cao, 7-8 Chuyên sâu. Mục 6 "Ứng dụng trí tuệ nhân tạo" thuộc khung NLS (TT 02/2025) — KHÁC với khung NLAI (QĐ 2422) ở trên; hai hệ mã độc lập, không gộp/nhầm lẫn định dạng.\n`
       +`Chọn bậc phù hợp với đối tượng học sinh ${v.students} của lớp ${grade} (ưu tiên Bậc 3-6 cho học sinh THPT đại trà; chỉ dùng Bậc 1-2 nếu học sinh yếu/mới bắt đầu, hoặc Bậc 7-8 nếu học sinh thực sự xuất sắc/chuyên sâu) — KHÔNG tự bịa bậc hay nội dung ngoài danh sách dưới đây.\n`
       +buildNLSText()+'\n';
  }
  out+='\n===== HẾT NGUỒN THAM CHIẾU BẮT BUỘC =====\n'
     +'QUY TẮC BẮT BUỘC KHI GẮN MÃ: (a) chỉ dùng đúng nguyên văn mã có trong bảng trên, tuyệt đối không tự tạo mã mới, không mượn mã của lớp/khối khác; (b) chỉ gắn mã vào một bước khi bước đó thực sự tạo ra hành vi học sinh quan sát được, khớp với đúng mô tả của mã; nếu không có, ghi "—", không cố gắn cho đủ; (c) việc lồng ghép NLS/NLAI KHÔNG được làm thay đổi hoặc gia tăng yêu cầu cần đạt của môn học đang soạn — chỉ dùng để củng cố, vận dụng; (d) TUYỆT ĐỐI không lập cột điểm/đầu điểm riêng cho NLS hoặc NLAI trong bất kỳ phần đánh giá nào của KHBD; (e) khi dùng yêu cầu cần đạt NLAI thuộc nội dung mở rộng (có tiền tố MR), phải ghi rõ đây là nội dung mở rộng, không bắt buộc.\n';
  return out;
}

function promptFor(v){const grade=clampGrade(v.grade);return `Bạn là chuyên gia hàng đầu về xây dựng Kế hoạch bài dạy tại Việt Nam. Hãy soạn KHBD năm học 2026–2027, tuyệt đối dựa trên tài liệu nguồn nếu có.
THÔNG TIN: Môn ${v.subject}; lớp ${grade}; bài ${v.lesson}; bộ sách ${v.book}; số tiết ${v.periods||'hãy xác định từ SGV/tài liệu'}; học sinh ${v.students}; sĩ số ${v.classSize}; thiết bị ${v.equipment}. Ghi chú: ${v.notes||'không'}.
YÊU CẦU BẮT BUỘC:
1) Ghi rõ căn cứ xác định số tiết; nếu nguồn thiếu thì ghi “đề xuất” và không bịa trang sách.
2) Bám sát đúng cấu trúc KHBD theo Phụ lục IV, Công văn số 5512/BGDĐT-GDTrH ngày 18/12/2020 dưới đây — không tự đổi tên đề mục cấp I/II/III, không tự đổi tên/số lượng 4 hoạt động (chỉ được thêm tên riêng thể hiện nội dung bài vào sau tên hoạt động gốc):
${KHBD_TEMPLATE_5512}
Sau Hoạt động 4 (Vận dụng), có thể thêm mục "Điều chỉnh sau bài dạy" (để trống hoặc ghi "..." vì đây là phần GV tự ghi sau khi dạy thực tế).
3) Trong mỗi hoạt động, mục d) Tổ chức thực hiện tuyệt đối không dùng bảng Markdown. Bắt buộc xuất một khối mã lessonflow chứa JSON hợp lệ theo mẫu: {"type":"lessonflow","rows":[{"step":"Bước 1: Giao nhiệm vụ học tập","teacherStudent":["GV giao nhiệm vụ cụ thể...","HS tiếp nhận và xác định yêu cầu..."],"product":["Câu trả lời hoặc sản phẩm dự kiến cụ thể..."],"competency":["Mã: hành vi quan sát được"]},{"step":"Bước 2: Thực hiện nhiệm vụ","teacherStudent":["GV theo dõi, hỗ trợ...","HS thực hiện..."],"product":["Kết quả dự kiến..."],"competency":["—"]},{"step":"Bước 3: Báo cáo, thảo luận","teacherStudent":["GV tổ chức báo cáo...","HS trình bày, phản biện..."],"product":["Nội dung báo cáo hoặc lời giải..."],"competency":["—"]},{"step":"Bước 4: Kết luận, nhận định","teacherStudent":["GV nhận xét và chuẩn hoá...","HS ghi nhận, tự sửa..."],"product":["Kiến thức chốt chính xác..."],"competency":["—"]}]}. Mỗi công thức trong JSON phải đặt giữa $...$ và gạch chéo ngược LaTeX phải viết thành hai gạch chéo ngược để JSON hợp lệ.
Bảng phải thể hiện rõ việc GV làm, việc HS làm, câu hỏi/nhiệm vụ, cách tổ chức, thời lượng và phân hoá cho đối tượng ${v.students}; phù hợp ${v.classSize} HS và thiết bị ${v.equipment}. Sản phẩm dự kiến phải đặt song song với từng bước, có nội dung, đáp án hoặc kiến thức chốt cụ thể, không chỉ ghi tên sản phẩm. Cột "competency" (NLS/NLAI) chỉ gắn khi có hành vi quan sát được và phải theo đúng QUY TẮC BẮT BUỘC KHI GẮN MÃ nêu trong khối nguồn tham chiếu bên dưới (nếu có); nếu không phát sinh ghi "—".
${buildStandardsBlock(v)}
4) ${$('includeDigital').checked?'Tích hợp NLS: chỉ dùng mã trong bảng NLS ở trên, đúng nhóm lớp NC1, chỉ gắn khi có hành vi quan sát được.':'Không bắt buộc tích hợp NLS.'} ${$('includeAI').checked?'Tích hợp NLAI: chỉ dùng mã trong bảng NLAI ở trên, đúng lớp '+grade+', có kiểm chứng sản phẩm AI (yêu cầu HS đối chiếu/kiểm tra lại kết quả do AI tạo ra), không gắn hình thức.':'Không bắt buộc tích hợp NLAI.'}
5) Mọi công thức nội dòng bắt buộc đặt giữa $...$; công thức riêng dòng đặt giữa $$...$$. Tuyệt đối không in lệnh LaTeX trần như \\frac, \\sqrt, \\lim ngoài dấu phân cách. QUAN TRỌNG — lỗi hay gặp cần tránh: bên trong $...$/$$...$$ PHẢI giữ nguyên dấu gạch chéo ngược "\" của mọi lệnh LaTeX (vec, in, mathbb, cdot, perp, Leftrightarrow, frac, widehat, overrightarrow...) ở TẤT CẢ các phần của tài liệu, kể cả các gạch đầu dòng văn xuôi ở mục a) Mục tiêu/b) Nội dung/c) Sản phẩm (không chỉ bên trong khối lessonflow). Viết ĐÚNG: "$\\vec{a} = k\\vec{b}$ ($k \\in \\mathbb{R}$, $\\vec{b} \\neq \\vec{0}$)"; "$\\widehat{AOB}$"; "$\\vec{IA}+\\vec{IB}+\\vec{IC}+\\vec{ID}=\\vec{0}$". KHÔNG được viết thành "$veca = kvecb$ ($k in mathbbR$)" hay "$vecIA+vecIB=vec0$" (thiếu dấu \\ sẽ làm hỏng công thức khi hiển thị).
6) BẮT BUỘC — không tuỳ chọn: với MỌI ví dụ, hoạt động hoặc bài luyện tập trong bài học có nội dung xét dấu đạo hàm, tìm khoảng đồng biến/nghịch biến, tìm cực trị, hoặc khảo sát sự biến thiên của hàm số, phải xuất kèm một khối mã mathviz type "variation" dựng bảng biến thiên tương ứng ngay trong "product" của bước đó — TUYỆT ĐỐI không chỉ mô tả bằng lời văn xuôi (như "lập bảng biến thiên", "xét dấu y'") mà bỏ qua việc dựng hình. Đây là yêu cầu bắt buộc cho toàn bộ bài học liên quan đến chuyên đề Tính đơn điệu, Cực trị, Giá trị lớn nhất/nhỏ nhất, Khảo sát và vẽ đồ thị hàm số — kể cả trong hoạt động hình thành kiến thức, ví dụ minh hoạ, luyện tập lẫn vận dụng. Khi cần bảng biến thiên, xuất khối mã mathviz với type "variation" theo ĐÚNG schema sau (KHÔNG dùng "columns"/"rows" cho loại này): {"type":"variation","title":"...","points":[...],"derivative":[...],"values":[...]}. "points" là N mốc x theo thứ tự tăng dần (thường bắt đầu "-∞" và kết thúc "+∞"). "derivative" PHẢI có đúng 2N-3 phần tử, xen kẽ [dấu khoảng 1, giá trị tại điểm 2, dấu khoảng 2, giá trị tại điểm 3, ..., dấu khoảng cuối] — nghĩa là dấu ở các vị trí chẵn (0,2,4...) ứng với khoảng GIỮA hai điểm liên tiếp, còn "0" (hoặc để trống nếu không đổi dấu) ở các vị trí lẻ ứng với TỪNG điểm tới hạn nằm giữa (không tính điểm đầu/cuối). "values" có đúng N phần tử, mỗi phần tử là giá trị y tại điểm tương ứng trong "points" (số, phân số dạng "a/b", biểu thức như "f(x_{1})", hoặc "+∞"/"-∞"); nếu hàm số có tiệm cận/gián đoạn ngay tại một điểm (ví dụ hàm phân thức), thay giá trị điểm đó bằng object {"left":"...","right":"..."} ghi giới hạn trái/phải. Mọi ký hiệu (points, values) chỉ chứa toán học thuần tuý, dùng ngoặc nhọn cho chỉ số nhiều ký tự ($x_{1}$), TUYỆT ĐỐI không chèn chữ mô tả tiếng Việt (Đ, CĐ, CT...) lẫn vào — muốn phân biệt nhiều điểm tới hạn thì đặt tên bằng chỉ số $x_{1}$, $x_{2}$... theo đúng thứ tự.
Ví dụ 1 điểm tới hạn (N=3, derivative có 2*3-3=3 phần tử): {"type":"variation","title":"Bảng biến thiên hàm số y=-x^2+2x+3","points":["-∞","1","+∞"],"derivative":["+","0","-"],"values":["-∞","4","-∞"]}.
Ví dụ 2 điểm tới hạn, một cực đại một cực tiểu (N=4, derivative có 2*4-3=5 phần tử): {"type":"variation","title":"Bảng biến thiên hàm số y=1/3x^3+3x^2+5x+2","points":["-∞","-5","-1","+∞"],"derivative":["+","0","-","0","+"],"values":["-∞","31/3","-1/3","+∞"]}.
Ví dụ có tiệm cận đứng (hàm phân thức, N=5 vì có thêm điểm tiệm cận x=1 xen giữa 2 điểm cực trị x=-1 và x=3, derivative có 2*5-3=7 phần tử): xét y=(x^2-2x+5)/(x-1) có y'=(x-3)(x+1)/(x-1)^2, y'=0 tại x=-1 và x=3, y không xác định tại x=1 (mẫu bằng 0). Vì (x-1)^2>0 nên dấu y' chỉ phụ thuộc (x-3)(x+1): âm khi -1<x<1 VÀ khi 1<x<3 (dấu KHÔNG đổi qua x=1, chỉ gián đoạn), dương khi x<-1 hoặc x>3. Tại x=1: giới hạn trái = -∞ (tử dương/mẫu→0⁻), giới hạn phải = +∞ (tử dương/mẫu→0⁺). Kết quả đúng — chú ý vị trí thứ 3 trong "derivative" (ứng với điểm tiệm cận x=1) PHẢI để "" (không phải "0", vì y' không xác định chứ không phải bằng 0 tại đó): {"type":"variation","title":"Bảng biến thiên hàm số y=(x^2-2x+5)/(x-1)","points":["-∞","-1","1","3","+∞"],"derivative":["+","0","-","","-","0","+"],"values":["-∞","-4",{"left":"-∞","right":"+∞"},"4","+∞"]}. QUY TRÌNH bắt buộc khi gặp hàm phân thức/có tiệm cận: (1) tính y' thật bằng đạo hàm, rút gọn về một phân thức; (2) liệt kê TẤT CẢ điểm y'=0 VÀ TẤT CẢ điểm hàm số không xác định, gộp chung và sắp xếp tăng dần vào "points" (không được thiếu điểm tiệm cận); (3) xét dấu y' trên từng khoảng bằng cách thay một giá trị x đại diện, không suy đoán; (4) tại điểm y'=0 ghi "0", tại điểm không xác định ghi "" (không ghi "0"); (5) tính giới hạn trái/phải thật tại điểm không xác định để điền {"left":...,"right":...} vào "values", không bịa.
Khi cần bảng xét dấu (không phải bảng biến thiên), dùng type "sign" với schema {"columns":[...],"rows":[{"label":"...","cells":[...]}]} — cột đầu "x" chỉ để hiển thị, mỗi "cells" phải có đúng số phần tử = số phần tử "columns" trừ 1, ví dụ: {"type":"sign","title":"...","columns":["x","-∞","-2","3","+∞"],"rows":[{"label":"f(x)","cells":["+","0","-","0","+"]}]} — nếu có nhiều hơn 1 điểm tới hạn liền kề cần thêm cột trống "" đại diện khoảng giữa như trên.
Đồ thị dùng {"type":"graph","title":"...","xMin":-5,"xMax":5,"yMin":-5,"yMax":5,"functions":[{"expr":"x^2-2*x-3","label":"f(x)","color":"#176fa8"}]}. Chỉ dùng biểu thức theo x với +,-,*,/,^, ngoặc và sin, cos, tan, sqrt, abs, exp, log.
7) Câu hỏi phải chính xác; tự giải và kiểm tra đáp án hai lần. Không sao chép máy móc giáo án tham khảo; không bịa dữ kiện từ nguồn. Đầu ra bằng Markdown, không mở đầu xã giao, phong cách ${$('style').value}.`}
const MAX_MODEL_ATTEMPTS=3; // Giới hạn số mô hình thử tuần tự, tránh giáo viên phải chờ hàng chục phút nếu key có nhiều model nhưng đều lỗi.
async function callGemini(v,key){const parts=[{text:promptFor(v)}];for(const f of selectedFiles){setProgress(25,'Đang đọc tài liệu...',f.name);parts.push(await filePart(f))}if(!availableModels.length)await scanModels(false);const selected=$('model').value,allCandidates=selected!=='auto'?[selected,...availableModels.map(m=>m.name).filter(n=>n!==selected)]:availableModels.map(m=>m.name);if(!allCandidates.length)throw new Error('Không tìm thấy mô hình Gemini đang hoạt động cho API key này');const candidates=allCandidates.slice(0,MAX_MODEL_ATTEMPTS),skipped=allCandidates.length-candidates.length;const errors=[];for(let i=0;i<candidates.length;i++){const fullName=candidates[i],model=fullName.replace(/^models\//,'');setProgress(48+Math.min(i,4)*5,'Đang chọn mô hình AI...',`Đang thử ${model}${i?` (dự phòng ${i}/${candidates.length-1})`:''}`);try{const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts}],generationConfig:{temperature:.25,maxOutputTokens:16384}})}),data=await res.json();if(!res.ok)throw new Error(data?.error?.message||`Lỗi HTTP ${res.status}`);const text=data.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('\n')||'';if(!text)throw new Error('Mô hình không trả về nội dung');setModelStatus(`Đang dùng ${model}`,'ok');if([...$('model').options].some(o=>o.value===fullName))$('model').value=fullName;return text}catch(err){errors.push(`${model}: ${err.message}`)}}throw new Error(`Đã thử ${candidates.length} mô hình nhưng đều chưa phản hồi${skipped?` (còn ${skipped} mô hình chưa thử, hãy chọn thủ công ở mục nâng cao)`:''}. ${errors.slice(0,2).join(' · ')}`)}
function fallback(v){const p=v.periods||'…',g=clampGrade(v.grade);return `# KẾ HOẠCH BÀI DẠY\n## ${v.subject.toUpperCase()} ${g} — ${v.lesson}\n**Bộ sách:** ${v.book}  \n**Thời lượng:** ${p} tiết ${v.periods?'':'(cần xác định từ SGV)'}  \n**Đối tượng:** ${v.students}; **Sĩ số:** ${v.classSize}  \n**Thiết bị:** ${v.equipment}\n\n> Đây là khung dự thảo tạo không dùng AI (chưa gắn mã NLS/NLAI vì không tra được bảng mã ở chế độ này). Hãy bổ sung API key miễn phí để hệ thống đọc sâu tài liệu, tạo nội dung đặc thù và gắn đúng mã NLS/NLAI theo lớp ${g}.\n\n## I. MỤC TIÊU\n### 1. Về kiến thức\n- Nội dung kiến thức cốt lõi của bài ${v.lesson} theo đúng yêu cầu cần đạt của chương trình môn học.\n### 2. Về năng lực\n- Năng lực chung: tự chủ và tự học; giao tiếp và hợp tác; giải quyết vấn đề và sáng tạo.\n- Năng lực đặc thù môn học cần phát triển qua bài học.\n### 3. Về phẩm chất\n- Chăm chỉ, trung thực, trách nhiệm trong học tập và hợp tác.\n\n## II. THIẾT BỊ DẠY HỌC VÀ HỌC LIỆU\n- Giáo viên: SGK, SGV, phiếu học tập, ${v.equipment}.\n- Học sinh: SGK, vở ghi, dụng cụ học tập.\n\n## III. TIẾN TRÌNH DẠY HỌC\n### 1. Hoạt động 1: Xác định vấn đề/nhiệm vụ học tập/Mở đầu\na) Mục tiêu — b) Nội dung — c) Sản phẩm — d) Tổ chức thực hiện (Giao nhiệm vụ → Thực hiện nhiệm vụ → Báo cáo, thảo luận → Kết luận, nhận định).\n\n### 2. Hoạt động 2: Hình thành kiến thức mới\na) Mục tiêu — b) Nội dung — c) Sản phẩm — d) Tổ chức thực hiện (4 bước như trên).\n\n### 3. Hoạt động 3: Luyện tập\na) Mục tiêu — b) Nội dung: hệ thống câu hỏi/bài tập phân hoá cho học sinh ${v.students} — c) Sản phẩm: đáp án, lời giải — d) Tổ chức thực hiện (4 bước như trên).\n\n### 4. Hoạt động 4: Vận dụng\na) Mục tiêu — b) Nội dung: vận dụng kiến thức vào tình huống thực tiễn — c) Sản phẩm: báo cáo — d) Tổ chức thực hiện: thường giao ngoài giờ học trên lớp, nộp báo cáo vào thời điểm phù hợp.\n\n*(Đánh giá thường xuyên được lồng ngay trong mục d) Tổ chức thực hiện của từng hoạt động — hỏi–đáp, viết, thực hành, sản phẩm học tập — theo đúng Phụ lục IV, Công văn 5512/BGDĐT-GDTrH; không lập cột điểm/đầu điểm riêng cho NLS/NLAI.)*\n\n## ĐIỀU CHỈNH SAU BÀI DẠY\n........................................................................`}
// Phòng hờ: model đôi khi làm mất dấu "\" của lệnh LaTeX khi viết văn xuôi (mục a/b/c ngoài
// bảng tổ chức thực hiện) — ví dụ "$\vec{a}=k\vec{b}$" bị trả về thành "$veca=kvecb$". Bên trong
// bảng (JSON lessonflow) hầu như không gặp vì model phải giữ đúng cú pháp JSON. Đây chỉ là lưới an
// toàn, KHÔNG thay thế việc dặn model giữ đúng "\" ngay trong prompt (xem promptFor()).
const LATEX_CMDS=['overrightarrow','widehat','mathbb','mathrm','Leftrightarrow','Rightarrow','leftrightarrow','rightarrow','overline','underline','forall','exists','angle','parallel','approx','equiv','notin','subset','infty','sqrt','frac','dfrac','left','right','quad','qquad','times','cdot','perp','cong','sim','circ','boxed','text','vec','hat','bar','sum','prod','int','alpha','beta','gamma','delta','theta','lambda','sigma','omega','phi','pi','leq','geq','neq','pm','mp','in'];
// Mẫu riêng hay gặp nhất ở bài vectơ: model làm mất CẢ "\" lẫn "{}" (vd "\vec{IA}" -> "vecIA",
// "\vec{0}" -> "vec0") — phải vá TRƯỚC lượt repairLatex chung ở trên (lượt chung chỉ vá được
// trường hợp còn giữ "{}", ví dụ "vec{a}" -> "\vec{a}", không tự đoán được ranh giới đối số nếu
// thiếu cả ngoặc). Chỉ áp dụng cho "vec" + (một chữ số 0) hoặc (cụm chữ hoa ngắn kiểu tên điểm
// AB, IA, OC'...) vì đây là dạng tên vectơ duy nhất xuất hiện trong nội dung hình học không gian.
const vecBareRe=/(^|[^\\}])vec(0|[A-Z][A-Za-z']{0,3}|[a-z]'?)\b/g;
const repairVecBare=s=>s.replace(vecBareRe,(m,pre,arg)=>pre+'\\vec{'+arg+'}');
const latexCmdRe=new RegExp('(^|[^\\\\a-zA-Z])('+LATEX_CMDS.join('|')+')(?=\\{|\\s|\\(|\\)|$|[+\\-=,.])','g');
const repairLatex=s=>repairVecBare(s).replace(latexCmdRe,(m,pre,cmd)=>pre+'\\'+cmd);
function inline(s){return esc(s).replace(/&lt;br\s*\/?&gt;/gi,'<br>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/`(.+?)`/g,'<code>$1</code>').replace(/\$\$([^$]+)\$\$/g,(m,g1)=>`<span class="math-display">\\[${repairLatex(g1)}\\]</span>`).replace(/\$([^$]+)\$/g,(m,g1)=>`<span class="math">\\(${repairLatex(g1)}\\)</span>`)}
function mdToHtml(md){const specs=[];md=md.replace(/```mathviz\s*([\s\S]*?)```/gi,(_,json)=>{const id=specs.push(json.trim())-1;return `\n@@MATHVIZ_${id}@@\n`});const lines=md.replace(/```[a-z]*\n?/g,'').replace(/```/g,'').split('\n');let out='',list=false;for(let i=0;i<lines.length;i++){let l=lines[i].trimEnd(),mv=l.trim().match(/^@@MATHVIZ_(\d+)@@$/);if(mv){if(list){out+='</ul>';list=false}out+=`<div class="mathviz" data-spec="${encodeURIComponent(specs[+mv[1]])}"></div>`;continue}if(l.startsWith('|')&&i+1<lines.length&&/^\|?[\s:|-]+\|?$/.test(lines[i+1].trim())){if(list){out+='</ul>';list=false}const rows=[];rows.push(l);i+=2;while(i<lines.length&&lines[i].trim().startsWith('|')){rows.push(lines[i].trim());i++}i--;out+='<table>';rows.forEach((r,ri)=>{const cells=r.replace(/^\||\|$/g,'').split('|');out+=`<tr>${cells.map(c=>`<${ri?'td':'th'}>${inline(c.trim())}</${ri?'td':'th'}>`).join('')}</tr>`});out+='</table>';continue}if(/^#{1,3} /.test(l)){if(list){out+='</ul>';list=false}const n=l.match(/^#+/)[0].length;out+=`<h${n}>${inline(l.slice(n+1))}</h${n}>`}else if(/^[-*] /.test(l)){if(!list){out+='<ul>';list=true}out+=`<li>${inline(l.slice(2))}</li>`}else if(/^\d+\. /.test(l)){if(list){out+='</ul>';list=false}out+=`<p>${inline(l)}</p>`}else if(l.startsWith('> ')){if(list){out+='</ul>';list=false}out+=`<blockquote>${inline(l.slice(2))}</blockquote>`}else if(!l){if(list){out+='</ul>';list=false}}else{if(list){out+='</ul>';list=false}out+=`<p>${inline(l)}</p>`}}if(list)out+='</ul>';return out}
function compileExpr(expr){let s=String(expr||'').toLowerCase().replace(/\^/g,'**').replace(/\bpi\b/g,'Math.PI');if(!/^[0-9x+\-*/().,\s*a-z]+$/.test(s))throw Error('Biểu thức không hợp lệ');for(const f of ['sin','cos','tan','sqrt','abs','exp','log'])s=s.replace(new RegExp(`\\b${f}\\b`,'g'),`Math.${f}`);const check=s.replace(/Math\.(?:PI|sin|cos|tan|sqrt|abs|exp|log)/g,'').replace(/x/g,'');if(/[a-z]/i.test(check))throw Error('Hàm chưa được hỗ trợ');return new Function('x',`"use strict";return (${s})`)}
const wrapMathCell=v=>{const s=String(v??'').trim();if(!s)return '';if(/^[+\-0↗↘↑↓∞]+$/.test(s))return esc(s);return s.includes('$')?inline(s):`$${esc(s)}$`};
// Nhãn đặt trong foreignObject để MathJax vẫn xử lý được $...$ bên trong SVG (phân số, chỉ số dưới...).
function svgLabel(cx,cy,content,anchor,w,h){w=w||100;h=h||24;const x=anchor==='start'?cx:anchor==='end'?cx-w:cx-w/2;const justify=anchor==='start'?'flex-start':anchor==='end'?'flex-end':'center';return `<foreignObject x="${x}" y="${cy-h/2}" width="${w}" height="${h}" style="overflow:visible"><div xmlns="http://www.w3.org/1999/xhtml" class="vt-label" style="justify-content:${justify}">${content}</div></foreignObject>`}
// Dựng bảng biến thiên dạng sơ đồ đường gấp khúc (đúng chuẩn SGK) từ schema {points,derivative,values}.
// points: N mốc x (thường có -∞/+∞ ở 2 đầu). derivative: đúng 2N-3 phần tử, xen kẽ dấu-khoảng/giá trị-tại-điểm.
// values: N giá trị y tương ứng từng điểm trong "points"; một phần tử có thể là {left,right} để biểu diễn
// điểm gián đoạn/tiệm cận (vd hàm phân thức) — khi đó vẽ dấu ngắt "‖" và tách 2 nhãn giá trị trái/phải.
function coerceLen(arr,n,fill){arr=Array.isArray(arr)?arr.slice():[];while(arr.length<n)arr.push(fill);if(arr.length>n)arr.length=n;return arr}
function buildVariationSVG(spec){
  const points=Array.isArray(spec.points)?spec.points:[];
  const N=points.length;
  if(N<2)return null;
  // Model đôi khi đếm lệch 1-2 phần tử trong "derivative"/"values" — tự đệm/cắt cho khớp thay vì
  // bỏ cuộc và báo lỗi ngay, để vẫn dựng được một sơ đồ có ích (có thể thiếu 1 dấu, còn hơn trắng trang).
  const deriv=coerceLen(spec.derivative,2*N-3,'');
  const values=coerceLen(spec.values,N,'');
  const W=760,leftLabel=40,rightPad=16,plotW=W-leftLabel-rightPad;
  const xAt=i=>leftLabel+(N===1?0:i*(plotW/(N-1)));
  const bandX=36,bandDeriv=56,bandVal=204,padTop=10,padBot=10;
  const yTop=padTop,derivTopY=yTop+bandX,valTopY=derivTopY+bandDeriv,valBotY=valTopY+bandVal,H=valBotY+padBot;
  const intervalSign=i=>deriv[2*i];
  let arriveLevel=[0],departLevel=[0];
  for(let i=0;i<N-1;i++){const s=intervalSign(i),d=s==='+'?1:s==='-'?-1:0,nextArrive=departLevel[i]+d;arriveLevel.push(nextArrive);const v=values[i+1];departLevel.push(v&&typeof v==='object'?(v.right==='+∞'?nextArrive+3:v.right==='-∞'?nextArrive-3:nextArrive):nextArrive)}
  const allLv=arriveLevel.concat(departLevel),minL=Math.min(...allLv),maxL=Math.max(...allLv),span=Math.max(1,maxL-minL);
  const yForLevel=lv=>valBotY-26-((lv-minL)/span)*(bandVal-52);
  const valLabel=i=>{const v=values[i];return (v&&typeof v==='object')?null:String(v)};
  const yArrive=i=>{const v=valLabel(i);if(v==='+∞')return valTopY+16;if(v==='-∞')return valBotY-16;return yForLevel(arriveLevel[i])};
  const yDepart=i=>{const v=valLabel(i);if(v==='+∞')return valTopY+16;if(v==='-∞')return valBotY-16;return yForLevel(departLevel[i])};
  let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(spec.title||'Bảng biến thiên')}">`;
  svg+=`<rect x="${leftLabel}" y="${yTop}" width="${plotW}" height="${valBotY-yTop}" class="vt-frame" fill="none" stroke="#333" stroke-width="1.2"/>`;
  svg+=`<line x1="${leftLabel}" y1="${derivTopY}" x2="${W-rightPad}" y2="${derivTopY}" class="vt-frame" stroke="#333" stroke-width="1.2"/>`;
  svg+=`<line x1="${leftLabel}" y1="${valTopY}" x2="${W-rightPad}" y2="${valTopY}" class="vt-frame" stroke="#333" stroke-width="1.2"/>`;
  points.forEach((_,i)=>{const x=xAt(i);svg+=`<line x1="${x}" y1="${yTop}" x2="${x}" y2="${valBotY}" class="vt-grid" stroke="#333" stroke-width="1"/>`});
  svg+=svgLabel(2,(yTop+derivTopY)/2,'$x$','start',36,20);
  svg+=svgLabel(2,(derivTopY+valTopY)/2,`$y'$`,'start',36,20);
  svg+=svgLabel(2,(valTopY+valBotY)/2,'$y$','start',36,20);
  points.forEach((p,i)=>{svg+=svgLabel(xAt(i),(yTop+derivTopY)/2,wrapMathCell(p),'middle',110,20)});
  for(let i=0;i<N-1;i++){const s=intervalSign(i);if(s)svg+=svgLabel((xAt(i)+xAt(i+1))/2,(derivTopY+valTopY)/2,wrapMathCell(s),'middle',60,20)}
  for(let i=1;i<N-1;i++){const v=deriv[2*i-1];if(v!==undefined)svg+=svgLabel(xAt(i),(derivTopY+valTopY)/2,wrapMathCell(v),'middle',60,20)}
  for(let i=0;i<N-1;i++){const x1=xAt(i),x2=xAt(i+1),y1=yDepart(i),y2=yArrive(i+1);svg+=`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="vt-path" fill="none" stroke="#164f75" stroke-width="1.8" stroke-linecap="round"/>`;const mx=(x1+x2)/2,my=(y1+y2)/2,ang=Math.atan2(y2-y1,x2-x1),ah=6,ax1=mx-ah*Math.cos(ang-0.4),ay1=my-ah*Math.sin(ang-0.4),ax2=mx-ah*Math.cos(ang+0.4),ay2=my-ah*Math.sin(ang+0.4);svg+=`<polygon points="${mx},${my} ${ax1},${ay1} ${ax2},${ay2}" class="vt-arrow" fill="#164f75"/>`}
  points.forEach((p,i)=>{const v=values[i],anchor=i===0?'start':(i===N-1?'end':'middle');if(v&&typeof v==='object'){const yL=yArrive(i),yR=yDepart(i),midY=(yL+yR)/2;svg+=svgLabel(xAt(i)-8,yL-14,wrapMathCell(v.left),'end',80,20);svg+=svgLabel(xAt(i)+8,yR-14,wrapMathCell(v.right),'start',80,20);svg+=`<line x1="${xAt(i)-6}" y1="${midY+11}" x2="${xAt(i)+2}" y2="${midY-11}" class="vt-path" stroke="#164f75" stroke-width="1.4"/><line x1="${xAt(i)-1}" y1="${midY+11}" x2="${xAt(i)+7}" y2="${midY-11}" class="vt-path" stroke="#164f75" stroke-width="1.4"/>`}else{svg+=svgLabel(xAt(i)+(i===0?6:i===N-1?-6:0),yArrive(i)-14,wrapMathCell(v),anchor,90,20)}});
  svg+='</svg>';
  return svg;
}
function renderMathViz(){document.querySelectorAll('.mathviz').forEach(el=>{try{const s=JSON.parse(decodeURIComponent(el.dataset.spec));if(s.type==='graph'){const W=760,H=390,p=38,x0=+s.xMin||-5,x1=+s.xMax||5,y0=+s.yMin||-5,y1=+s.yMax||5,X=x=>p+(x-x0)/(x1-x0)*(W-2*p),Y=y=>H-p-(y-y0)/(y1-y0)*(H-2*p);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(s.title||'Đồ thị hàm số')}"><defs><clipPath id="plotClip"><rect x="${p}" y="${p}" width="${W-2*p}" height="${H-2*p}"/></clipPath></defs><rect x="${p}" y="${p}" width="${W-2*p}" height="${H-2*p}" class="plot-bg"/>`;for(let k=Math.ceil(x0);k<=Math.floor(x1);k++)svg+=`<line x1="${X(k)}" y1="${p}" x2="${X(k)}" y2="${H-p}" class="grid-line"/>`;for(let k=Math.ceil(y0);k<=Math.floor(y1);k++)svg+=`<line x1="${p}" y1="${Y(k)}" x2="${W-p}" y2="${Y(k)}" class="grid-line"/>`;svg+=`<line x1="${p}" y1="${Y(0)}" x2="${W-p}" y2="${Y(0)}" class="axis"/><line x1="${X(0)}" y1="${p}" x2="${X(0)}" y2="${H-p}" class="axis"/>`;for(const fn of s.functions||[]){const f=compileExpr(fn.expr);let d='',pen=false;for(let i=0;i<=700;i++){const x=x0+(x1-x0)*i/700,y=f(x),ok=Number.isFinite(y)&&y>=y0-(y1-y0)&&y<=y1+(y1-y0);if(ok){d+=(pen?'L':'M')+X(x).toFixed(2)+' '+Y(y).toFixed(2);pen=true}else pen=false}svg+=`<path d="${d}" stroke="${esc(fn.color||'#176fa8')}" class="plot-path" clip-path="url(#plotClip)"/>`}el.innerHTML=`<div class="mathviz-title">${esc(s.title||'Đồ thị')}</div>${svg}</svg><div class="mathviz-legend">${(s.functions||[]).map(f=>`<span style="--c:${esc(f.color||'#176fa8')}">$${esc(f.label||f.expr)}$</span>`).join('')}</div>`}else if(s.type==='variation'&&Array.isArray(s.points)){const svg=buildVariationSVG(s);if(!svg)throw new Error('variation schema không hợp lệ');el.innerHTML=`<div class="mathviz-title">${esc(s.title||'Bảng biến thiên')}</div><div class="mathviz-scroll vt-scroll">${svg}</div>`}else{const cols=s.columns||[],rows=s.rows||[];el.innerHTML=`<div class="mathviz-title">${esc(s.title|| (s.type==='sign'?'Bảng xét dấu':'Bảng biến thiên'))}</div><div class="mathviz-scroll"><table class="variation-table"><thead><tr>${cols.map(c=>`<th>${wrapMathCell(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th>${wrapMathCell(r.label)}</th>${(r.cells||[]).map(c=>`<td class="variation-cell">${wrapMathCell(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}}catch(e){el.innerHTML='<p class="mathviz-error">Không dựng được hình toán học này. Vui lòng tạo lại nội dung.</p>'}})}
function showResult(md){rawMarkdown=md;$('progress').hidden=true;$('emptyState').hidden=true;$('result').innerHTML=mdToHtml(md);renderMathViz();$('result').hidden=false;$('resultActions').hidden=false;const typeset=()=>window.MathJax?.typesetPromise?window.MathJax.typesetPromise([$('result')]).catch(()=>{}):null;typeset()||setTimeout(typeset,800);$('result').scrollIntoView({behavior:'smooth',block:'start'});saveDraft()}
$('lessonForm').onsubmit=async e=>{e.preventDefault();const v=values(),key=$('apiKey').value.trim();$('generateBtn').disabled=true;try{setProgress(10,'Đang kiểm tra nguồn...','Chuẩn bị dữ liệu bài dạy');let md;if(key){md=await callGemini(v,key);if(!md)throw new Error('AI chưa trả về nội dung')}else{await new Promise(r=>setTimeout(r,700));setProgress(70,'Đang tạo khung dự thảo...','Dùng chế độ cơ bản không cần API key');await new Promise(r=>setTimeout(r,600));md=fallback(v)}setProgress(94,'Đang hoàn thiện...','Kiểm tra cấu trúc bản kế hoạch');await new Promise(r=>setTimeout(r,450));showResult(md);toast(key?'Đã tạo KHBD bằng AI':'Đã tạo khung dự thảo cơ bản')}catch(err){$('progress').hidden=true;$('emptyState').hidden=false;toast(err.message||'Có lỗi xảy ra')}finally{$('generateBtn').disabled=false}}
$('copyBtn').onclick=async()=>{await navigator.clipboard.writeText(rawMarkdown);toast('Đã sao chép nội dung')};
$('printBtn').onclick=()=>window.print();
$('wordBtn').onclick=()=>{const v=values(),body=$('result').innerHTML;const html=`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><style>@page{size:A4;margin:2cm}body{font-family:'Times New Roman';font-size:13pt;line-height:1.35}h1{text-align:center;color:#164f75;font-size:16pt}h2{color:#176fa8;font-size:14pt}h3{font-size:13pt}table{border-collapse:collapse;width:100%}td,th{border:1px solid #555;padding:5px;vertical-align:top}th{background:#164f75;color:white}.math{font-family:'Cambria Math'}</style></head><body>${body}</body></html>`;const blob=new Blob(['\ufeff',html],{type:'application/msword'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`KHBD_${v.subject}_${v.grade}_${v.lesson.replace(/[^a-zA-Z0-9À-ỹ]+/g,'_').slice(0,55)}.doc`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Đã tạo tệp Word')};

/* ===== Tự động lưu nháp (localStorage) =====
   Lưu dữ liệu form + kết quả vừa soạn để giáo viên không mất công nếu lỡ tay refresh/đóng tab.
   KHÔNG lưu apiKey — giữ đúng cam kết "khóa chỉ tồn tại trong phiên trình duyệt" đã ghi trong giao diện.
   Không lưu tệp đính kèm (File object không phù hợp để lưu localStorage và có thể rất nặng). */
const DRAFT_KEY='khbd_draft_v1';
function saveDraft(){try{const draft={values:values(),includeDigital:$('includeDigital').checked,includeAI:$('includeAI').checked,style:$('style').value,resultMd:rawMarkdown||null,ts:Date.now()};localStorage.setItem(DRAFT_KEY,JSON.stringify(draft))}catch(_){/* localStorage đầy hoặc bị chặn (chế độ ẩn danh) — bỏ qua, không ảnh hưởng chức năng chính */}}
function loadDraft(){try{const raw=localStorage.getItem(DRAFT_KEY);return raw?JSON.parse(raw):null}catch(_){return null}}
function clearDraft(){try{localStorage.removeItem(DRAFT_KEY)}catch(_){}}
function scheduleDraftSave(){clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,500)}
$('lessonForm').addEventListener('input',scheduleDraftSave);
$('lessonForm').addEventListener('change',scheduleDraftSave);
function initDraft(){const d=loadDraft();if(!d)return;try{Object.entries(d.values||{}).forEach(([k,v])=>{if(v&&fields.includes(k)&&$(k))$(k).value=v});if(typeof d.includeDigital==='boolean')$('includeDigital').checked=d.includeDigital;if(typeof d.includeAI==='boolean')$('includeAI').checked=d.includeAI;if(d.style)$('style').value=d.style;if(d.resultMd)showResult(d.resultMd);$('clearDraftBtn').hidden=false;toast('Đã khôi phục bản nháp gần nhất (chưa gồm tệp đính kèm)')}catch(_){}}
$('clearDraftBtn').onclick=()=>{clearDraft();location.reload()};
initDraft();
