/* V28 login: hai vai trò, phiên đăng nhập HttpOnly. */
(function(){'use strict';const $=id=>document.getElementById(id);let role='teacher';
function msg(t,c=''){$('loginMessage').textContent=t;$('loginMessage').className='login-message '+c}
function tab(r){role=r;document.querySelectorAll('[data-login-role]').forEach(b=>{const on=b.dataset.loginRole===r;b.classList.toggle('active',on);b.setAttribute('aria-selected',on)});$('loginTitle').textContent=r==='admin'?'Đăng nhập Quản trị':'Đăng nhập Giáo viên';$('loginUsername').placeholder=r==='admin'?'Tên đăng nhập quản trị':'Tên đăng nhập giáo viên';$('loginSubmit').textContent=r==='admin'?'Vào trang quản trị':'Vào Trợ lý soạn KHBD';msg('')}
function open(r,u){document.body.classList.add('authenticated');$('loginScreen').hidden=true;$('logoutBtn').hidden=false;$('accountBadge').hidden=false;$('accountBadge').textContent=(r==='admin'?'Quản trị: ':'Giáo viên: ')+u}
async function session(){try{const r=await fetch('/api/auth-session',{credentials:'same-origin'}),d=await r.json();if(r.ok&&d.authenticated)open(d.role,d.user);else $('loginScreen').hidden=false}catch(_){$('loginScreen').hidden=false;msg('Không kết nối được máy chủ đăng nhập.','error')}}
async function submit(e){e.preventDefault();const b=$('loginSubmit'),username=$('loginUsername').value.trim(),password=$('loginPassword').value;if(!username||!password)return msg('Hãy nhập đầy đủ tên đăng nhập và mật khẩu.','error');b.disabled=true;b.textContent='Đang xác thực…';try{const r=await fetch('/api/auth-login',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({role,username,password})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Đăng nhập không thành công');$('loginPassword').value='';open(d.role,d.user)}catch(x){msg(x.message,'error')}finally{b.disabled=false;b.textContent=role==='admin'?'Vào trang quản trị':'Vào Trợ lý soạn KHBD'}}
async function logout(){await fetch('/api/auth-logout',{method:'POST',credentials:'same-origin'}).catch(()=>{});document.body.classList.remove('authenticated');$('logoutBtn').hidden=true;$('accountBadge').hidden=true;$('loginScreen').hidden=false;tab('teacher')}
function init(){document.querySelectorAll('[data-login-role]').forEach(b=>b.onclick=()=>tab(b.dataset.loginRole));$('loginForm').onsubmit=submit;$('logoutBtn').onclick=logout;$('forgotPassword').onclick=()=>msg('Hãy liên hệ Quản trị để được cấp lại mật khẩu. Không gửi mật khẩu qua tin nhắn công khai.','info');tab('teacher');session()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init()})();