/* V27.2 — chỉnh, thêm, nhân bản, xóa graph / variation / sign trên markdown gốc. */
(function(){'use strict';
const $=id=>document.getElementById(id),S={blocks:[],index:0};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function scan(md){const out=[],re=/```mathviz\s*\r?\n([\s\S]*?)```/gi;let m;while((m=re.exec(String(md||''))))try{const spec=JSON.parse(typeof repairJsonEscapes==='function'?repairJsonEscapes(m[1]):m[1]);if(['graph','variation','sign'].includes(spec.type))out.push({start:m.index,end:re.lastIndex,spec})}catch(_){}return out}
const csv=v=>(Array.isArray(v)?v:[]).map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join(', ');
function asymText(a){return (a||[]).map(x=>x.type==='vertical'?`đứng:${x.value}`:x.type==='horizontal'?`ngang:${x.value}`:`xiên:${x.slope}:${x.intercept}`).join('\n')}
function fields(s){const h=`<label>Tiêu đề<input data-k="title" value="${esc(s.title||'')}"></label>`;if(s.type==='graph')return h+`<div class="grid two"><label>Biểu thức<input data-k="expr" value="${esc(s.functions?.[0]?.expr||s.expression||s.expr||'')}"></label><label>Nhãn hàm số<input data-k="label" value="${esc(s.functions?.[0]?.label||'')}"></label></div><div class="grid four"><label>x min<input type="number" step="any" data-k="xMin" value="${s.xMin??-5}"></label><label>x max<input type="number" step="any" data-k="xMax" value="${s.xMax??5}"></label><label>y min<input type="number" step="any" data-k="yMin" value="${s.yMin??-5}"></label><label>y max<input type="number" step="any" data-k="yMax" value="${s.yMax??5}"></label></div><label>Tiệm cận — mỗi dòng: đứng:2, ngang:1 hoặc xiên:1:-3<textarea data-k="asymptotes">${esc(asymText(s.asymptotes))}</textarea></label>`;if(s.type==='variation')return h+`<label>Biểu thức để vẽ đồ thị<input data-k="expr" value="${esc(s.expr||'')}"></label><label>Các mốc x, cách nhau bằng dấu phẩy<input data-k="points" value="${esc(csv(s.points))}"></label><label>Dấu đạo hàm<input data-k="derivative" value="${esc(csv(s.derivative))}"></label><label>Giá trị f(x)<input data-k="values" value="${esc(csv(s.values))}"></label>`;const r=s.rows?.[0]||{};return h+`<label>Các mốc x<input data-k="columns" value="${esc(csv(s.columns))}"></label><label>Tên hàng<input data-k="rowLabel" value="${esc(r.label||"f'(x)")}"></label><label>Dấu và giá trị<input data-k="cells" value="${esc(csv(r.cells))}"></label>`}
function list(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}
function parseAsym(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(x=>{const p=x.split(':').map(y=>y.trim()),t=p[0].toLowerCase();if(t==='đứng'||t==='dung'||t==='vertical')return {type:'vertical',value:Number(p[1])};if(t==='ngang'||t==='horizontal')return {type:'horizontal',value:Number(p[1])};if(t==='xiên'||t==='xien'||t==='oblique')return {type:'oblique',slope:Number(p[1]),intercept:Number(p[2])};throw new Error('Dòng tiệm cận chưa đúng: '+x)})}
function read(){const o=structuredClone(S.blocks[S.index].spec),g=k=>$('mathEditorFields').querySelector(`[data-k="${k}"]`)?.value;o.title=g('title');if(o.type==='graph'){const e=g('expr'),b=o.functions?.[0]||{};o.functions=[{...b,expr:e,label:g('label')||b.label||e},...(o.functions||[]).slice(1)];['xMin','xMax','yMin','yMax'].forEach(k=>o[k]=Number(g(k)));o.asymptotes=parseAsym(g('asymptotes'))}else if(o.type==='variation'){o.expr=g('expr');o.points=list(g('points'));o.derivative=list(g('derivative'));o.values=list(g('values'))}else{o.columns=list(g('columns'));o.rows=[{...(o.rows?.[0]||{}),label:g('rowLabel'),cells:list(g('cells'))},...(o.rows||[]).slice(1)]}return o}
function preview(){const b=$('mathEditorPreview');try{const s=read(),svg=s.type==='graph'?buildGraphSVG(s):s.type==='variation'?buildVariationSVG(s):buildSignSVG(s);b.innerHTML=svg||'<p>Chưa đủ dữ liệu để dựng hình.</p>';window.MathJax?.typesetPromise?.([b])}catch(e){b.innerHTML=`<p class="mathviz-error">${esc(e.message||e)}</p>`}}
function load(i){S.index=Number(i)||0;const s=S.blocks[S.index].spec;$('mathEditorFields').innerHTML=fields(s);$('mathEditorJson').value=JSON.stringify(s,null,2);$('mathEditorFields').querySelectorAll('input,textarea').forEach(x=>x.oninput=preview);preview()}
function open(){S.blocks=scan(typeof rawMarkdown==='string'?rawMarkdown:'');$('mathBlockSelect').innerHTML=S.blocks.length?S.blocks.map((b,i)=>`<option value="${i}">${i+1}. ${esc(b.spec.title||b.spec.type)}</option>`).join(''):'<option>Chưa có đối tượng</option>';$('duplicateMathObject').disabled=$('deleteMathObject').disabled=!S.blocks.length;if(S.blocks.length)load(Math.min(S.index,S.blocks.length-1));else{$('mathEditorFields').innerHTML='<p>Chọn loại hình rồi bấm “Thêm” để tạo đối tượng đầu tiên.</p>';$('mathEditorPreview').innerHTML='';$('mathEditorJson').value=''}if(!$('mathEditorDialog').open)$('mathEditorDialog').showModal()}
function apply(){try{const b=S.blocks[S.index],s=read(),r='```mathviz\n'+JSON.stringify(s,null,2)+'\n```';rawMarkdown=rawMarkdown.slice(0,b.start)+r+rawMarkdown.slice(b.end);$('mathEditorDialog').close();showResult(rawMarkdown,validatePlan(rawMarkdown,values(),false));window.khbdSaveVersion?.(true)}catch(e){alert('Không thể áp dụng: '+(e.message||e))}}
const templates={graph:{type:'graph',title:'Đồ thị hàm số',xMin:-5,xMax:5,yMin:-5,yMax:5,asymptotes:[],functions:[{expr:'x^2',label:'y=x^2',color:'#176fa8'}]},variation:{type:'variation',title:'Bảng biến thiên',expr:'x^3-3*x',points:['-\\infty','-1','1','+\\infty'],derivative:['+','0','-','0','+'],values:['-\\infty','2','-2','+\\infty']},sign:{type:'sign',title:'Bảng xét dấu',columns:['-\\infty','0','+\\infty'],rows:[{label:"f'(x)",cells:['-','0','+']}]}};
function insertSpec(spec,after){const r='```mathviz\n'+JSON.stringify(spec,null,2)+'\n```',pos=after&&S.blocks.length?S.blocks[S.index].end:rawMarkdown.length;rawMarkdown=rawMarkdown.slice(0,pos)+'\n\n'+r+'\n'+rawMarkdown.slice(pos);$('mathEditorDialog').close();showResult(rawMarkdown,validatePlan(rawMarkdown,values(),false));open();S.index=after?Math.min(S.index+1,S.blocks.length-1):S.blocks.length-1;$('mathBlockSelect').value=S.index;load(S.index)}
function add(){insertSpec(structuredClone(templates[$('newMathType').value]),false)}
function duplicate(){insertSpec(structuredClone(read()),true)}
function remove(){if(!confirm('Xóa đối tượng Toán học đang chọn?'))return;const b=S.blocks[S.index];rawMarkdown=rawMarkdown.slice(0,b.start)+rawMarkdown.slice(b.end);$('mathEditorDialog').close();showResult(rawMarkdown,validatePlan(rawMarkdown,values(),false));window.khbdSaveVersion?.(true)}
function loadJson(){try{S.blocks[S.index].spec=JSON.parse($('mathEditorJson').value);load(S.index)}catch(e){alert('JSON chưa hợp lệ: '+e.message)}}
$('mathEditBtn').onclick=open;$('mathBlockSelect').onchange=e=>load(e.target.value);$('previewMathEdit').onclick=preview;$('applyMathEdit').onclick=apply;$('applyMathJson').onclick=loadJson;$('addMathObject').onclick=add;$('duplicateMathObject').onclick=duplicate;$('deleteMathObject').onclick=remove;$('cancelMathEdit').onclick=()=>$('mathEditorDialog').close();window.khbdMathEditor={scan,open};
})();
