/* V27.1 — chỉnh trực quan graph / variation / sign trên markdown gốc. */
(function(){'use strict';
const $=id=>document.getElementById(id),S={blocks:[],index:0};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function scan(md){const out=[],re=/```mathviz\s*\r?\n([\s\S]*?)```/gi;let m;while((m=re.exec(String(md||''))))try{const spec=JSON.parse(typeof repairJsonEscapes==='function'?repairJsonEscapes(m[1]):m[1]);if(['graph','variation','sign'].includes(spec.type))out.push({start:m.index,end:re.lastIndex,spec})}catch(_){}return out}
const csv=v=>(Array.isArray(v)?v:[]).map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join(', ');
function fields(s){const h=`<label>Tiêu đề<input data-k="title" value="${esc(s.title||'')}"></label>`;if(s.type==='graph')return h+`<div class="grid two"><label>Biểu thức<input data-k="expr" value="${esc(s.functions?.[0]?.expr||s.expression||s.expr||'')}"></label><label>Nhãn hàm số<input data-k="label" value="${esc(s.functions?.[0]?.label||'')}"></label></div><div class="grid four"><label>x min<input type="number" step="any" data-k="xMin" value="${s.xMin??-5}"></label><label>x max<input type="number" step="any" data-k="xMax" value="${s.xMax??5}"></label><label>y min<input type="number" step="any" data-k="yMin" value="${s.yMin??-5}"></label><label>y max<input type="number" step="any" data-k="yMax" value="${s.yMax??5}"></label></div>`;if(s.type==='variation')return h+`<label>Biểu thức để vẽ đồ thị<input data-k="expr" value="${esc(s.expr||'')}"></label><label>Các mốc x, cách nhau bằng dấu phẩy<input data-k="points" value="${esc(csv(s.points))}"></label><label>Dấu đạo hàm<input data-k="derivative" value="${esc(csv(s.derivative))}"></label><label>Giá trị f(x)<input data-k="values" value="${esc(csv(s.values))}"></label>`;const r=s.rows?.[0]||{};return h+`<label>Các mốc x<input data-k="columns" value="${esc(csv(s.columns))}"></label><label>Tên hàng<input data-k="rowLabel" value="${esc(r.label||"f'(x)")}"></label><label>Dấu và giá trị<input data-k="cells" value="${esc(csv(r.cells))}"></label>`}
function list(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}
function read(){const o=structuredClone(S.blocks[S.index].spec),g=k=>$('mathEditorFields').querySelector(`[data-k="${k}"]`)?.value;o.title=g('title');if(o.type==='graph'){const e=g('expr'),b=o.functions?.[0]||{};o.functions=[{...b,expr:e,label:g('label')||b.label||e},...(o.functions||[]).slice(1)];['xMin','xMax','yMin','yMax'].forEach(k=>o[k]=Number(g(k)))}else if(o.type==='variation'){o.expr=g('expr');o.points=list(g('points'));o.derivative=list(g('derivative'));o.values=list(g('values'))}else{o.columns=list(g('columns'));o.rows=[{...(o.rows?.[0]||{}),label:g('rowLabel'),cells:list(g('cells'))},...(o.rows||[]).slice(1)]}return o}
function preview(){const b=$('mathEditorPreview');try{const s=read(),svg=s.type==='graph'?buildGraphSVG(s):s.type==='variation'?buildVariationSVG(s):buildSignSVG(s);b.innerHTML=svg||'<p>Chưa đủ dữ liệu để dựng hình.</p>';window.MathJax?.typesetPromise?.([b])}catch(e){b.innerHTML=`<p class="mathviz-error">${esc(e.message||e)}</p>`}}
function load(i){S.index=Number(i)||0;const s=S.blocks[S.index].spec;$('mathEditorFields').innerHTML=fields(s);$('mathEditorJson').value=JSON.stringify(s,null,2);$('mathEditorFields').querySelectorAll('input').forEach(x=>x.oninput=preview);preview()}
function open(){S.blocks=scan(typeof rawMarkdown==='string'?rawMarkdown:'');if(!S.blocks.length){alert('Bản kế hoạch chưa có đồ thị, bảng biến thiên hoặc bảng xét dấu.');return}$('mathBlockSelect').innerHTML=S.blocks.map((b,i)=>`<option value="${i}">${i+1}. ${esc(b.spec.title||b.spec.type)}</option>`).join('');load(0);$('mathEditorDialog').showModal()}
function apply(){try{const b=S.blocks[S.index],s=read(),r='```mathviz\n'+JSON.stringify(s,null,2)+'\n```';rawMarkdown=rawMarkdown.slice(0,b.start)+r+rawMarkdown.slice(b.end);$('mathEditorDialog').close();showResult(rawMarkdown,validatePlan(rawMarkdown,values(),false));window.khbdSaveVersion?.(true)}catch(e){alert('Không thể áp dụng: '+(e.message||e))}}
function loadJson(){try{S.blocks[S.index].spec=JSON.parse($('mathEditorJson').value);load(S.index)}catch(e){alert('JSON chưa hợp lệ: '+e.message)}}
$('mathEditBtn').onclick=open;$('mathBlockSelect').onchange=e=>load(e.target.value);$('previewMathEdit').onclick=preview;$('applyMathEdit').onclick=apply;$('applyMathJson').onclick=loadJson;$('cancelMathEdit').onclick=()=>$('mathEditorDialog').close();window.khbdMathEditor={scan,open};
})();
